services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: vetclinic_db
      POSTGRES_USER: vet_user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: